import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header } from "./components/header/Header";
import { getHeaderData } from "./providers/header-data";
import { CartProvider } from "./providers/cart-context";
import { CartTray } from "./components/cart/CartTray";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { collections, activeCustomer, activeOrder } = await getHeaderData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <Header
            activeCustomer={activeCustomer}
            collections={collections}
            cartQuantity={activeOrder?.totalQuantity || 0}
          />
          <CartTray />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
