#!/bin/bash

# Script para actualizar el comando de inicio del servicio Baileys Worker en Railway
# Nota: Railway CLI no soporta actualizar start command directamente
# Este script muestra las instrucciones y verifica el estado actual

echo "=========================================="
echo "Actualizar Baileys Worker Start Command"
echo "=========================================="
echo ""
echo "Railway CLI no permite actualizar el start command directamente."
echo "Debes hacerlo desde el Railway Dashboard."
echo ""
echo "Pasos:"
echo "1. Ve a: https://railway.app/project/99370a3c-0bda-423f-b4ff-7697000cfcb1"
echo "2. Haz clic en el servicio 'Baileys Worker'"
echo "3. Ve a Settings → Deploy"
echo "4. En 'Start Command', cambia a:"
echo "   cd apps/backend && npm run worker:baileys"
echo "5. Guarda y redeplega"
echo ""
echo "Comando correcto:"
echo "  cd apps/backend && npm run worker:baileys"
echo ""
echo "Comando incorrecto (actual):"
echo "  cd apps/backend && npm run start:prod"
echo ""
echo "=========================================="
echo "Verificación después de actualizar:"
echo "=========================================="
echo ""
echo "Ejecuta estos comandos para verificar:"
echo ""
echo "  railway link --service 'Baileys Worker'"
echo "  railway logs"
echo ""
echo "Deberías ver:"
echo "  ✅ Starting Baileys worker service (standalone)"
echo "  ✅ Prisma Client initialized and connected to database"
echo "  ✅ Baileys worker service is running"
echo ""
echo "NO deberías ver:"
echo "  ❌ [Nest] Starting Nest application..."
echo "  ❌ [InstanceLoader] ConfigHostModule..."
echo ""

